'use strict';
/**
 * Export the Fakemon data in the format the Pokemon Showdown *client* expects.
 *
 * The Teambuilder and the battle UI live in the separate `pokemon-showdown-client`
 * repository, which ships its own copy of the dex. Running this writes drop-in
 * replacements so the client shows only the custom game:
 *
 *   node tools/fakemon/export-client.js [outputDir]
 *
 * Copy the resulting files over `play.pokemonshowdown.com/data/` in the client
 * repo. Because the originals are replaced wholesale, the Teambuilder can only
 * offer Fakemon Pokemon, moves, abilities and items.
 *
 * Battle behaviour is unaffected: the server is always the authority, and the
 * `Fakemon Standard` rule rejects anything else regardless of what a client sends.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const { Dex } = require(path.join(ROOT, 'dist', 'sim'));

const OUT = process.argv[2] || path.join(ROOT, 'dist-client', 'data');

/** The client only renders data, so drop every function and internal field. */
function plain(value) {
	if (Array.isArray(value)) return value.map(plain);
	if (value && typeof value === 'object') {
		const out = {};
		for (const [key, inner] of Object.entries(value)) {
			if (typeof inner === 'function') continue;
			if (key.startsWith('on') || key === 'condition' || key === 'effectType') continue;
			out[key] = plain(inner);
		}
		return out;
	}
	if (typeof value === 'function') return undefined;
	return value;
}

function write(file, exportName, table) {
	fs.mkdirSync(OUT, { recursive: true });
	const body = JSON.stringify(table, null, 1);
	fs.writeFileSync(
		path.join(OUT, file),
		`// Generated by tools/fakemon/export-client.js - do not edit by hand.\n` +
		`exports.${exportName} = ${body};\n`
	);
	return Object.keys(table).length;
}

function main() {
	const dex = Dex.mod('fakemon');
	dex.includeData();

	const pokedex = {};
	for (const [id, entry] of Object.entries(dex.data.Pokedex)) {
		pokedex[id] = plain(entry);
	}

	const movedex = {};
	for (const [id, entry] of Object.entries(dex.data.Moves)) {
		// Original moves kept only for their mechanics, and the internal helper
		// moves, are all tagged Custom and must not appear in the UI.
		if (entry.isNonstandard === 'Custom') continue;
		movedex[id] = plain(entry);
	}

	const abilities = {};
	for (const [id, entry] of Object.entries(dex.data.Abilities)) {
		abilities[id] = plain(entry);
	}

	const items = {};
	for (const [id, entry] of Object.entries(dex.data.Items)) {
		items[id] = plain(entry);
	}

	const counts = {
		pokedex: write('pokedex.js', 'BattlePokedex', pokedex),
		moves: write('moves.js', 'BattleMovedex', movedex),
		abilities: write('abilities.js', 'BattleAbilities', abilities),
		items: write('items.js', 'BattleItems', items),
		learnsets: write('learnsets.js', 'BattleLearnsets', plain(dex.data.Learnsets)),
		typechart: write('typechart.js', 'BattleTypeChart', plain(dex.data.TypeChart)),
		formatsData: write('formats-data.js', 'BattleFormatsData', plain(dex.data.FormatsData)),
	};

	// The client resolves sprites by name; this maps every species to its asset.
	const sprites = {};
	for (const [id, entry] of Object.entries(dex.data.Pokedex)) {
		sprites[id] = {
			front: `assets/pokemon/${id}.png`,
			icon: `assets/pokemon-icons/${id}.png`,
		};
	}
	write('fakemon-sprites.js', 'FakemonSprites', sprites);

	console.log(`Wrote client data to ${OUT}`);
	for (const [name, count] of Object.entries(counts)) {
		console.log(`  ${name}: ${count}`);
	}
	console.log(`  sprites: ${Object.keys(sprites).length}`);
}

/**
 * Write the data bundle the built-in web client (`server/static/`) loads.
 * Called from `node build`, so the client can never drift from the dex.
 */
/**
 * Which shelf an item belongs on. The teambuilder groups its item picker by
 * this, so the 240-item list stays readable.
 */
const ITEM_GROUPS = (() => {
	const groups = new Map();
	const tables = [
		['Food', require('../../dist/data/mods/fakemon/items-food').FoodItems],
		['Consumable', require('../../dist/data/mods/fakemon/items-consumables').ConsumableItems],
		['Battle gear', require('../../dist/data/mods/fakemon/items-battle').BattleItems],
		['Permanent gear', require('../../dist/data/mods/fakemon/items-permanent').PermanentItems],
	];
	for (const [group, table] of tables) {
		for (const id of Object.keys(table)) groups.set(id, group);
	}
	return groups;
})();

function itemGroup(id, entry) {
	if (entry.megaStone) return 'Mega Stone';
	return ITEM_GROUPS.get(id) || 'Core';
}

function buildStaticClientData() {
	const dex = Dex.mod('fakemon');
	dex.includeData();
	const index = require(path.join(ROOT, 'tools', 'fakemon', 'raw', 'index.json'));

	const pokedex = {};
	for (const [id, entry] of Object.entries(dex.data.Pokedex)) {
		const species = dex.species.get(id);
		pokedex[id] = {
			name: species.name,
			types: species.types,
			baseStats: species.baseStats,
			abilities: species.abilities,
			weightkg: species.weightkg,
			prevo: species.prevo || undefined,
			// `evos` is an empty array for final evolutions, which is truthy.
			evos: species.evos?.length ? species.evos : undefined,
			isMega: species.isMega || undefined,
			baseSpecies: species.baseSpecies !== species.name ? species.baseSpecies : undefined,
			requiredItem: species.requiredItem || undefined,
			battleOnly: entry.battleOnly || undefined,
			tier: dex.data.FormatsData[id]?.tier,
		};
	}

	const moves = {};
	for (const [id, entry] of Object.entries(dex.data.Moves)) {
		if (entry.isNonstandard === 'Custom') continue; // mechanics-only originals
		const move = dex.moves.get(id);
		moves[id] = {
			name: move.name, type: move.type, category: move.category,
			basePower: move.basePower, accuracy: move.accuracy, pp: move.pp,
			priority: move.priority, target: move.target,
			desc: entry.shortDesc || entry.desc || '',
		};
	}

	const abilities = {};
	for (const [id, entry] of Object.entries(dex.data.Abilities)) {
		if (id === 'noability') continue;
		abilities[id] = {
			name: entry.name,
			desc: entry.shortDesc || entry.desc || '',
			isMega: Object.keys(index.megaAbilities).includes(id),
		};
	}

	const items = {};
	for (const [id, entry] of Object.entries(dex.data.Items)) {
		items[id] = {
			name: entry.name, desc: entry.desc || '',
			megaStone: entry.megaStone || undefined,
			group: itemGroup(id, entry),
		};
	}

	const learnsets = {};
	for (const [id, entry] of Object.entries(dex.data.Learnsets)) {
		learnsets[id] = Object.keys(entry.learnset || {}).filter(moveId => moves[moveId]);
	}

	const bundle = {
		pokedex, moves, abilities, items, learnsets,
		typechart: dex.data.TypeChart,
		megas: index.megas,
		formats: Dex.formats.all()
			.filter(format => format.mod === 'fakemon' && format.effectType === 'Format')
			.map(format => ({
				id: format.id, name: format.name,
				gameType: format.gameType || 'singles',
				team: format.team || null,
			})),
	};

	const outDir = path.join(ROOT, 'server', 'static', 'data');
	fs.mkdirSync(outDir, { recursive: true });
	fs.writeFileSync(
		path.join(outDir, 'fakemon-data.js'),
		`// Generated by tools/fakemon/export-client.js during \`node build\` - do not edit.\n` +
		`window.FakemonData = ${JSON.stringify(bundle)};\n`
	);
	writeAssetManifest(dex, index);

	return {
		pokedex: Object.keys(pokedex).length, moves: Object.keys(moves).length,
		abilities: Object.keys(abilities).length, items: Object.keys(items).length,
	};
}

/**
 * Rewrites `assets/manifest.json`: the expected image path of every entry in the
 * game. Generated rather than hand-kept so it can never drift from the dex, and
 * so "which files do I still have to draw" stays answerable with one file.
 */
function writeAssetManifest(dex, index) {
	const { ASSET_PATHS } = require(path.join(ROOT, 'dist', 'data', 'mods', 'fakemon', 'assets'));
	const pathFor = (kind, name) => `${ASSET_PATHS[kind]}/${dex.toID(name)}.png`;
	const section = (kind, names) => Object.fromEntries(names.map(n => [n, pathFor(kind, n)]));

	const speciesNames = Object.keys(dex.data.Pokedex).map(id => dex.species.get(id).name);
	// Only the selectable moves - the whitelisted mechanic providers nobody can
	// pick do not need artwork.
	const moveNames = [...index.genericMoves, ...Object.keys(index.signatureMoves)]
		.map(id => dex.moves.get(id).name);
	const abilityNames = Object.keys(dex.data.Abilities)
		.filter(id => id !== 'noability').map(id => dex.abilities.get(id).name);
	const itemIds = Object.keys(dex.data.Items);

	const manifest = {
		placeholder: `${ASSET_PATHS.placeholder}`,
		pokemon: section('pokemon', speciesNames),
		pokemonIcons: section('pokemonIcons', speciesNames),
		moves: section('moves', moveNames),
		abilities: section('abilities', abilityNames),
		items: section('items', itemIds.map(id => dex.items.get(id).name)),
		megaStones: section('mega', itemIds
			.filter(id => dex.data.Items[id].megaStone)
			.map(id => dex.items.get(id).name)),
	};
	fs.writeFileSync(
		path.join(ROOT, 'assets', 'manifest.json'),
		`${JSON.stringify(manifest, null, 1)}\n`
	);
}

exports.buildStaticClientData = buildStaticClientData;

if (require.main === module) {
	main();
	const counts = buildStaticClientData();
	console.log(`Wrote server/static/data/fakemon-data.js`, counts);
}
